char = "#"

print(f" {char*8}")
print(f" {char*2}")
print(f" {char*2}")
print(f" {char*2}")
print(f" {char*8}")
print("")

print(f" {char*8}")
print(f" {char*2}" , "  " , f"{char*2}")
print(f" {char*2}" , "  " , f"{char*2}")
print(f" {char*2}" , "  " , f"{char*2}")
print(f" {char*2}" , "  " , f"{char*2}")
print(f" {char*8}")
print("")
print(f" {char*8}")
print(f" {char*2}" , "  " , f"{char*2}")
print(f" {char*2}" , "   " , f"{char*2}")
print(f" {char*2}" , "    " , f"{char*2}")
print(f" {char*2}" , "   " , f"{char*2}")
print(f" {char*2}" , "  " , f"{char*2}")
print(f" {char*2}" , " " , f"{char*2}")
print(f" {char*2}" , "" , f"{char*2}")
print("")
print(f" {char*8}")
print(f" {char*2}")
print(f" {char*8}")
print(f" {char*2}")
print(f" {char*8}")


